version: '3.8'

services:
  mysql:
    image: mysql-custom
    container_name: prestashop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - prestashop-net

  prestashop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prestashop-app
    environment:
      DB_SERVER: mysql
      DB_NAME: prestashop
      DB_USER: prestashop
      DB_PASSWORD: prestashop
      PS_INSTALL_AUTO: 1
      PS_LANGUAGE: fr
      PS_COUNTRY: FR
      PS_SHOP_NAME: "MaBoutique"
      PS_ADMIN_EMAIL: "admin@example.com"
      PS_ADMIN_PASSWD: "admin123"
      PS_TIMEZONE: Europe/Paris
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - prestashop_data:/var/www/html
    networks:
      - prestashop-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: prestashop-phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      PMA_PROTOCOL: http  # Assurez-vous d'utiliser HTTP
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - prestashop-net

networks:
  prestashop-net:

volumes:
  mysql_data:
  prestashop_data:
  mysql_tmp:
